# Generated by Django 5.1.15 on 2026-07-13 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quotes", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="quotationitem",
            name="unit_label",
            field=models.CharField(
                blank=True, default="", max_length=40, verbose_name="medida"
            ),
        ),
    ]
