# Generated by Django 5.1.15 on 2026-06-29 20:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0001_initial"),
        ("inventory", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="BranchTransfer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("folio", models.CharField(max_length=30, unique=True)),
                ("date", models.DateTimeField(verbose_name="fecha")),
                ("sent_at", models.DateTimeField(blank=True, null=True)),
                ("received_at", models.DateTimeField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pendiente", "Pendiente"),
                            ("en_transito", "En tránsito"),
                            ("recibida", "Recibida"),
                            ("cancelada", "Cancelada"),
                        ],
                        default="pendiente",
                        max_length=20,
                    ),
                ),
                (
                    "notes",
                    models.TextField(blank=True, null=True, verbose_name="notas"),
                ),
                (
                    "reason_cancelled",
                    models.TextField(
                        blank=True, null=True, verbose_name="motivo cancelación"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "from_branch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="transfers_out",
                        to="core.branch",
                    ),
                ),
                (
                    "received_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="transfers_received",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "sent_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="transfers_sent",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "to_branch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="transfers_in",
                        to="core.branch",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="transfers_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "transferencia",
                "verbose_name_plural": "transferencias",
                "ordering": ["-date", "-id"],
            },
        ),
        migrations.CreateModel(
            name="BranchTransferItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity_base", models.DecimalField(decimal_places=4, max_digits=12)),
                (
                    "quantity_input",
                    models.DecimalField(decimal_places=4, max_digits=12),
                ),
                ("unit_label", models.CharField(blank=True, max_length=30, null=True)),
                (
                    "units_factor",
                    models.DecimalField(decimal_places=4, default=1, max_digits=12),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="transfer_items",
                        to="inventory.product",
                    ),
                ),
                (
                    "transfer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="transfers.branchtransfer",
                    ),
                ),
            ],
            options={
                "verbose_name": "partida de transferencia",
                "verbose_name_plural": "partidas de transferencia",
            },
        ),
        migrations.AddIndex(
            model_name="branchtransfer",
            index=models.Index(
                fields=["status", "date"], name="transfers_b_status_56c7d2_idx"
            ),
        ),
    ]
