# Generated by Django 5.2.15 on 2026-07-03 10:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SupplierBill",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "supplier_name",
                    models.CharField(max_length=200, verbose_name="proveedor"),
                ),
                (
                    "invoice_number",
                    models.CharField(
                        blank=True,
                        max_length=80,
                        null=True,
                        verbose_name="número de factura",
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=14, verbose_name="total"
                    ),
                ),
                ("paid_on", models.DateField(verbose_name="fecha de pago")),
                (
                    "payment_method",
                    models.CharField(
                        choices=[
                            ("efectivo", "Efectivo"),
                            ("cheque", "Cheque"),
                            ("transferencia", "Transferencia"),
                            ("tarjeta", "Tarjeta"),
                            ("otro", "Otro"),
                        ],
                        default="efectivo",
                        max_length=20,
                        verbose_name="forma de pago",
                    ),
                ),
                (
                    "notes",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="nota"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="supplier_bills",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "factura de proveedor",
                "verbose_name_plural": "facturas de proveedor",
                "ordering": ["-paid_on", "-created_at"],
                "indexes": [
                    models.Index(
                        fields=["paid_on"], name="supplierbil_paid_on_8a7393_idx"
                    ),
                    models.Index(
                        fields=["supplier_name"], name="supplierbil_supplie_192282_idx"
                    ),
                ],
            },
        ),
    ]
