# Generated by Django 5.1.15 on 2026-07-06 10:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("supplierbills", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SupplierFund",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "opening_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=14,
                        verbose_name="monto inicial",
                    ),
                ),
                (
                    "added_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=14,
                        verbose_name="aportes",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("abierto", "Abierto"), ("cerrado", "Cerrado")],
                        default="abierto",
                        max_length=20,
                    ),
                ),
                (
                    "opened_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="abierto el"),
                ),
                (
                    "closed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="cerrado el"
                    ),
                ),
                (
                    "closing_notes",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="notas de cierre",
                    ),
                ),
                (
                    "opened_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="supplier_funds",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "fondo de proveedores",
                "verbose_name_plural": "fondos de proveedores",
                "ordering": ["-opened_at"],
            },
        ),
        migrations.AddField(
            model_name="supplierbill",
            name="fund",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="bills",
                to="supplierbills.supplierfund",
            ),
        ),
    ]
