# Generated by Django 5.1.15 on 2026-06-29 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="CompanySetting",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "commercial_name",
                    models.CharField(
                        default="Mi Ferretería",
                        max_length=255,
                        verbose_name="nombre comercial",
                    ),
                ),
                (
                    "legal_name",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="razón social",
                    ),
                ),
                (
                    "tax_id",
                    models.CharField(default="CF", max_length=30, verbose_name="NIT"),
                ),
                (
                    "tax_regime",
                    models.CharField(
                        default="PEQUENO_CONTRIBUYENTE",
                        max_length=40,
                        verbose_name="régimen",
                    ),
                ),
                (
                    "address",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="dirección"
                    ),
                ),
                (
                    "department",
                    models.CharField(
                        blank=True,
                        max_length=120,
                        null=True,
                        verbose_name="departamento",
                    ),
                ),
                (
                    "municipality",
                    models.CharField(
                        blank=True, max_length=120, null=True, verbose_name="municipio"
                    ),
                ),
                (
                    "postal_code",
                    models.CharField(
                        blank=True,
                        max_length=10,
                        null=True,
                        verbose_name="código postal",
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        blank=True, max_length=30, null=True, verbose_name="teléfono"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=255, null=True, verbose_name="correo"
                    ),
                ),
                ("logo_path", models.CharField(blank=True, max_length=255, null=True)),
                ("country_code", models.CharField(default="GT", max_length=3)),
                ("currency_code", models.CharField(default="GTQ", max_length=3)),
                (
                    "default_tax_rate",
                    models.DecimalField(
                        decimal_places=2, default=12, max_digits=5, verbose_name="IVA %"
                    ),
                ),
                (
                    "prices_include_tax",
                    models.BooleanField(
                        default=True, verbose_name="precios incluyen IVA"
                    ),
                ),
                (
                    "phrases",
                    models.JSONField(blank=True, null=True, verbose_name="frases SAT"),
                ),
                (
                    "fel_yearly_quota",
                    models.PositiveIntegerField(
                        default=0, verbose_name="cupo anual FEL"
                    ),
                ),
                ("fel_cycle_month", models.PositiveSmallIntegerField(default=1)),
                ("fel_cycle_day", models.PositiveSmallIntegerField(default=1)),
                ("printer_mode", models.CharField(default="system", max_length=20)),
                ("printer_ip", models.CharField(blank=True, max_length=45, null=True)),
                ("printer_port", models.PositiveSmallIntegerField(default=9100)),
                ("printer_width", models.PositiveSmallIntegerField(default=80)),
                ("printer_auto_cut", models.BooleanField(default=True)),
                ("zebra_mode", models.CharField(default="system", max_length=20)),
                ("zebra_ip", models.CharField(blank=True, max_length=45, null=True)),
                ("zebra_port", models.PositiveSmallIntegerField(default=9100)),
                ("zebra_label_width", models.PositiveSmallIntegerField(default=50)),
                ("zebra_label_height", models.PositiveSmallIntegerField(default=25)),
                ("zebra_dpi", models.PositiveSmallIntegerField(default=203)),
                ("public_catalog_enabled", models.BooleanField(default=False)),
                ("public_catalog_show_prices", models.BooleanField(default=True)),
                (
                    "public_catalog_title",
                    models.CharField(blank=True, max_length=180, null=True),
                ),
                ("public_catalog_intro", models.TextField(blank=True, null=True)),
                (
                    "public_catalog_whatsapp",
                    models.CharField(blank=True, max_length=30, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "configuración de empresa",
                "verbose_name_plural": "configuración de empresa",
            },
        ),
    ]
