# Generated by Django 5.2.15 on 2026-06-30 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_companysetting"),
    ]

    operations = [
        migrations.AlterField(
            model_name="companysetting",
            name="commercial_name",
            field=models.CharField(
                default="Ferretería Central",
                max_length=255,
                verbose_name="nombre comercial",
            ),
        ),
    ]
