# Generated by Django 5.1.15 on 2026-07-21 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_permisos_cuentas_devoluciones"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="pin_hash",
            field=models.CharField(blank=True, default="", max_length=128),
        ),
    ]
