# Generated by Django 5.2.15 on 2026-07-21 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_user_pin_hash"),
    ]

    operations = [
        migrations.AddField(
            model_name="companysetting",
            name="pin_quick_login",
            field=models.BooleanField(default=True),
        ),
    ]
