# Generated by Django 5.2.15 on 2026-07-21 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_companysetting_pin_quick_login"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="is_device",
            field=models.BooleanField(
                default=False, verbose_name="cuenta de equipo (caja)"
            ),
        ),
    ]
