# Generated by Django 5.2.15 on 2026-07-25 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0007_user_is_device"),
    ]

    operations = [
        migrations.AddField(
            model_name="companysetting",
            name="pos_max_discount_percent",
            field=models.DecimalField(
                decimal_places=2,
                default=25,
                max_digits=5,
                verbose_name="descuento máx. sin autorización (%)",
            ),
        ),
    ]
