# Generated by Django 5.1.15 on 2026-08-26 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0012_permiso_etiquetar"),
    ]

    operations = [
        migrations.AddField(
            model_name="companysetting",
            name="printer_protocol",
            field=models.CharField(default="https", max_length=8),
        ),
    ]
