# Generated by Django 5.1.15 on 2026-09-02 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0014_permiso_devolucion_sin_ticket"),
    ]

    operations = [
        migrations.AddField(
            model_name="companysetting",
            name="pos_require_cash_received",
            field=models.BooleanField(
                default=False, verbose_name="obligar efectivo recibido"
            ),
        ),
    ]
