# Generated by Django 5.1.15 on 2026-09-21 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0015_companysetting_pos_require_cash_received"),
    ]

    operations = [
        migrations.AddField(
            model_name="companysetting",
            name="pos_multiple_payment_methods",
            field=models.BooleanField(
                default=False, verbose_name="aceptar otros métodos de pago"
            ),
        ),
    ]
