# Generated by Django 5.1.15 on 2026-09-21 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0016_companysetting_pos_multiple_payment_methods"),
    ]

    operations = [
        migrations.AddField(
            model_name="companysetting",
            name="pos_min_profit_percent",
            field=models.DecimalField(
                decimal_places=2,
                default=10,
                max_digits=5,
                verbose_name="ganancia mín. sin autorización (%)",
            ),
        ),
    ]
