# Generated by Django 5.1.15 on 2026-09-21 19:49

from decimal import Decimal

from django.db import migrations, models


def _bajar_descuento_maximo(apps, schema_editor):
    """El tope de descuento se había subido a 75% como parche para no frenar los
    productos baratos. Con el nuevo "colchón" en quetzales ya no hace falta, así
    que se devuelve a 25% (solo si estaba por encima, para no pisar un ajuste
    deliberado más bajo). Migración de una sola vez."""
    CompanySetting = apps.get_model("core", "CompanySetting")
    CompanySetting.objects.filter(pos_max_discount_percent__gt=Decimal("25")).update(
        pos_max_discount_percent=Decimal("25")
    )


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0017_companysetting_pos_min_profit_percent"),
    ]

    operations = [
        migrations.AddField(
            model_name="companysetting",
            name="pos_discount_free_amount",
            field=models.DecimalField(
                decimal_places=2,
                default=200,
                max_digits=12,
                verbose_name="descuento sin autorización hasta (Q)",
            ),
        ),
        migrations.RunPython(_bajar_descuento_maximo, migrations.RunPython.noop),
    ]
