# Generated by Django 5.1.15 on 2026-09-21 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0018_companysetting_pos_discount_free_amount"),
    ]

    operations = [
        migrations.AlterField(
            model_name="companysetting",
            name="pos_discount_free_amount",
            field=models.DecimalField(
                decimal_places=2,
                default=200,
                max_digits=12,
                verbose_name="descuento sin autorización hasta (Q) [obsoleto]",
            ),
        ),
        migrations.AlterField(
            model_name="companysetting",
            name="pos_max_discount_percent",
            field=models.DecimalField(
                decimal_places=2,
                default=25,
                max_digits=5,
                verbose_name="descuento máx. sin autorización (%) [obsoleto]",
            ),
        ),
    ]
