# Generated by Django 5.1.15 on 2026-09-21 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0019_marcar_obsoletos_descuento"),
    ]

    operations = [
        migrations.AddField(
            model_name="companysetting",
            name="pos_min_profit_amount",
            field=models.DecimalField(
                decimal_places=2,
                default=100,
                max_digits=12,
                verbose_name="ganancia mín. sin autorización (Q)",
            ),
        ),
    ]
