# Generated by Django 5.1.15 on 2026-09-23 21:50

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0020_companysetting_pos_min_profit_amount"),
    ]

    operations = [
        migrations.AddField(
            model_name="companysetting",
            name="pos_profit_tiers",
            field=models.JSONField(
                blank=True,
                default=core.models.default_profit_tiers,
                verbose_name="ganancia mínima por rango de precio",
            ),
        ),
    ]
