# Generated by Django 5.1.15 on 2026-09-24 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0021_companysetting_pos_profit_tiers"),
    ]

    operations = [
        migrations.AddField(
            model_name="companysetting",
            name="trash_retention_days",
            field=models.PositiveSmallIntegerField(
                default=30, verbose_name="días en la papelera antes de borrar"
            ),
        ),
    ]
