# Generated by Django 5.2.15 on 2026-06-30 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sales", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="saleitem",
            name="units_factor",
            field=models.DecimalField(decimal_places=4, default=1, max_digits=12),
        ),
    ]
