# Generated by Django 5.2.15 on 2026-07-03 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sales", "0002_alter_saleitem_units_factor"),
    ]

    operations = [
        migrations.AddField(
            model_name="sale",
            name="offline_uuid",
            field=models.CharField(
                blank=True, editable=False, max_length=64, null=True, unique=True
            ),
        ),
    ]
