# Generated by Django 5.1.15 on 2026-06-29 20:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0001_initial"),
        ("inventory", "0001_initial"),
        ("partners", "0001_initial"),
        ("sales", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SaleReturn",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("folio", models.CharField(max_length=30, unique=True)),
                ("date", models.DateTimeField(verbose_name="fecha")),
                (
                    "reason_type",
                    models.CharField(
                        choices=[
                            ("equivocacion", "Equivocación"),
                            ("defectuoso", "Defectuoso"),
                            ("no_satisfecho", "No satisfecho"),
                            ("sin_ticket", "Sin ticket"),
                            ("otro", "Otro"),
                        ],
                        default="equivocacion",
                        max_length=30,
                        verbose_name="motivo",
                    ),
                ),
                (
                    "reason",
                    models.TextField(blank=True, null=True, verbose_name="detalle"),
                ),
                (
                    "refund_method",
                    models.CharField(
                        choices=[
                            ("efectivo", "Efectivo"),
                            ("tarjeta", "Tarjeta"),
                            ("transferencia", "Transferencia"),
                            ("credito_nota", "Nota de crédito"),
                        ],
                        default="efectivo",
                        max_length=30,
                        verbose_name="reembolso",
                    ),
                ),
                (
                    "subtotal",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "discount",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=12,
                        verbose_name="descuento",
                    ),
                ),
                (
                    "tax",
                    models.DecimalField(
                        decimal_places=2, default=0, max_digits=12, verbose_name="IVA"
                    ),
                ),
                (
                    "total",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("procesada", "Procesada"),
                            ("cancelada", "Cancelada"),
                        ],
                        default="procesada",
                        max_length=20,
                    ),
                ),
                (
                    "notes",
                    models.TextField(blank=True, null=True, verbose_name="notas"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "branch",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="sale_returns",
                        to="core.branch",
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="sale_returns",
                        to="partners.customer",
                    ),
                ),
                (
                    "sale",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="returns",
                        to="sales.sale",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="sale_returns",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "devolución",
                "verbose_name_plural": "devoluciones",
                "ordering": ["-date", "-id"],
            },
        ),
        migrations.CreateModel(
            name="SaleReturnItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity", models.DecimalField(decimal_places=4, max_digits=12)),
                ("unit_price", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "discount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                ("subtotal", models.DecimalField(decimal_places=2, max_digits=12)),
                ("unit_label", models.CharField(blank=True, max_length=30, null=True)),
                (
                    "units_factor",
                    models.DecimalField(decimal_places=4, default=1, max_digits=12),
                ),
                ("tax_type", models.CharField(default="iva", max_length=20)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="return_items",
                        to="inventory.product",
                    ),
                ),
                (
                    "sale_item",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="return_items",
                        to="sales.saleitem",
                    ),
                ),
                (
                    "sale_return",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="salereturns.salereturn",
                    ),
                ),
            ],
            options={
                "verbose_name": "partida de devolución",
                "verbose_name_plural": "partidas de devolución",
            },
        ),
        migrations.AddIndex(
            model_name="salereturn",
            index=models.Index(
                fields=["sale", "status"], name="salereturns_sale_id_2b0341_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="salereturn",
            index=models.Index(fields=["date"], name="salereturns_date_5a71c3_idx"),
        ),
    ]
