# Generated by Django 5.1.15 on 2026-06-29 17:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Brand",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=255, unique=True, verbose_name="nombre"
                    ),
                ),
                (
                    "description",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="descripción",
                    ),
                ),
                ("active", models.BooleanField(default=True, verbose_name="activa")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "marca",
                "verbose_name_plural": "marcas",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=255, unique=True, verbose_name="nombre"
                    ),
                ),
                (
                    "description",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="descripción",
                    ),
                ),
                ("active", models.BooleanField(default=True, verbose_name="activa")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "categoría",
                "verbose_name_plural": "categorías",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Unit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=255, unique=True, verbose_name="nombre"
                    ),
                ),
                (
                    "abbreviation",
                    models.CharField(max_length=10, verbose_name="abreviatura"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "unidad",
                "verbose_name_plural": "unidades",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sku",
                    models.CharField(max_length=60, unique=True, verbose_name="SKU"),
                ),
                (
                    "barcode",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        max_length=60,
                        null=True,
                        verbose_name="código de barras",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        db_index=True, max_length=180, verbose_name="nombre"
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="descripción"),
                ),
                (
                    "base_unit_label",
                    models.CharField(
                        default="unidad", max_length=30, verbose_name="unidad base"
                    ),
                ),
                (
                    "container_label",
                    models.CharField(
                        blank=True, max_length=30, null=True, verbose_name="empaque"
                    ),
                ),
                (
                    "container_factor",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        max_digits=16,
                        null=True,
                        verbose_name="factor de empaque",
                    ),
                ),
                (
                    "container_price",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=12,
                        null=True,
                        verbose_name="precio por empaque",
                    ),
                ),
                (
                    "tax_type",
                    models.CharField(
                        choices=[("iva", "Gravado con IVA"), ("exento", "Exento")],
                        default="iva",
                        max_length=20,
                        verbose_name="tipo de impuesto",
                    ),
                ),
                (
                    "purchase_price",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=12,
                        verbose_name="precio de compra",
                    ),
                ),
                (
                    "sale_price",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=12,
                        verbose_name="precio de venta",
                    ),
                ),
                (
                    "wholesale_price",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=12,
                        null=True,
                        verbose_name="precio mayorista",
                    ),
                ),
                (
                    "wholesale_min_quantity",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=12,
                        null=True,
                        verbose_name="cantidad mín. mayorista",
                    ),
                ),
                (
                    "contractor_price",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=12,
                        null=True,
                        verbose_name="precio constructor",
                    ),
                ),
                (
                    "container_wholesale_price",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=12,
                        null=True,
                        verbose_name="precio empaque mayorista",
                    ),
                ),
                (
                    "container_contractor_price",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=12,
                        null=True,
                        verbose_name="precio empaque constructor",
                    ),
                ),
                (
                    "stock",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=12,
                        verbose_name="existencia",
                    ),
                ),
                (
                    "min_stock",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=12,
                        verbose_name="existencia mínima",
                    ),
                ),
                (
                    "sells_by_measure",
                    models.BooleanField(
                        default=False, verbose_name="se vende por medida"
                    ),
                ),
                (
                    "measure_step",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        max_digits=12,
                        null=True,
                        verbose_name="paso de medida",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="products/",
                        verbose_name="imagen",
                    ),
                ),
                ("active", models.BooleanField(default=True, verbose_name="activo")),
                (
                    "public_visible",
                    models.BooleanField(
                        default=True, verbose_name="visible en catálogo público"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "brand",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="products",
                        to="inventory.brand",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="products",
                        to="inventory.category",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="products_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "producto",
                "verbose_name_plural": "productos",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="ProductPresentation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("label", models.CharField(max_length=30, verbose_name="etiqueta")),
                (
                    "units_factor",
                    models.DecimalField(
                        decimal_places=4, max_digits=10, verbose_name="unidades base"
                    ),
                ),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2, max_digits=12, verbose_name="precio"
                    ),
                ),
                (
                    "display_order",
                    models.PositiveSmallIntegerField(default=0, verbose_name="orden"),
                ),
                ("active", models.BooleanField(default=True, verbose_name="activa")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="presentations",
                        to="inventory.product",
                    ),
                ),
            ],
            options={
                "verbose_name": "presentación",
                "verbose_name_plural": "presentaciones",
                "ordering": ["display_order"],
            },
        ),
        migrations.CreateModel(
            name="ProductSubstitute",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "priority",
                    models.PositiveIntegerField(default=1, verbose_name="prioridad"),
                ),
                (
                    "note",
                    models.CharField(
                        blank=True, max_length=120, null=True, verbose_name="nota"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="substitute_links",
                        to="inventory.product",
                    ),
                ),
                (
                    "substitute",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="substitute_of_links",
                        to="inventory.product",
                    ),
                ),
            ],
            options={
                "ordering": ["priority"],
                "unique_together": {("product", "substitute")},
            },
        ),
        migrations.AddField(
            model_name="product",
            name="substitutes",
            field=models.ManyToManyField(
                blank=True,
                related_name="substituted_by",
                through="inventory.ProductSubstitute",
                to="inventory.product",
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="unit",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="products",
                to="inventory.unit",
            ),
        ),
        migrations.CreateModel(
            name="InventoryMovement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("entrada", "Entrada"),
                            ("salida", "Salida"),
                            ("ajuste", "Ajuste"),
                        ],
                        max_length=10,
                        verbose_name="tipo",
                    ),
                ),
                (
                    "quantity",
                    models.DecimalField(
                        decimal_places=2, max_digits=12, verbose_name="cantidad"
                    ),
                ),
                (
                    "previous_stock",
                    models.DecimalField(decimal_places=2, max_digits=12),
                ),
                ("new_stock", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "reason",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="motivo"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "branch",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="inventory_movements",
                        to="core.branch",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="inventory_movements",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="movements",
                        to="inventory.product",
                    ),
                ),
            ],
            options={
                "verbose_name": "movimiento de inventario",
                "verbose_name_plural": "movimientos de inventario",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["product", "created_at"],
                        name="inventory_i_product_c37810_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="ProductStock",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "stock",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "min_stock",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "location",
                    models.CharField(
                        blank=True, max_length=60, null=True, verbose_name="ubicación"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "branch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="product_stocks",
                        to="core.branch",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stocks",
                        to="inventory.product",
                    ),
                ),
            ],
            options={
                "verbose_name": "existencia por sucursal",
                "verbose_name_plural": "existencias por sucursal",
                "unique_together": {("product", "branch")},
            },
        ),
    ]
