# Generated by Django 5.2.15 on 2026-06-30 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="inventorymovement",
            name="new_stock",
            field=models.DecimalField(decimal_places=4, max_digits=14),
        ),
        migrations.AlterField(
            model_name="inventorymovement",
            name="previous_stock",
            field=models.DecimalField(decimal_places=4, max_digits=14),
        ),
        migrations.AlterField(
            model_name="product",
            name="min_stock",
            field=models.DecimalField(
                decimal_places=4,
                default=0,
                max_digits=14,
                verbose_name="existencia mínima",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="stock",
            field=models.DecimalField(
                decimal_places=4, default=0, max_digits=14, verbose_name="existencia"
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="substitutes",
            field=models.ManyToManyField(
                blank=True,
                related_name="substituted_by",
                through="inventory.ProductSubstitute",
                through_fields=("product", "substitute"),
                to="inventory.product",
            ),
        ),
        migrations.AlterField(
            model_name="productstock",
            name="min_stock",
            field=models.DecimalField(decimal_places=4, default=0, max_digits=14),
        ),
        migrations.AlterField(
            model_name="productstock",
            name="stock",
            field=models.DecimalField(decimal_places=4, default=0, max_digits=14),
        ),
    ]
