# Generated by Django 5.2.15 on 2026-07-21 23:15

from django.db import migrations, models


def backfill(apps, schema_editor):
    """Rellena search_index de todos los productos existentes."""
    from core.textsearch import search_norm
    Product = apps.get_model("inventory", "Product")
    to_update = []
    for p in Product.objects.all().only("id", "name", "sku", "barcode", "container_label"):
        p.search_index = search_norm(p.name, p.sku, p.barcode, p.container_label)
        to_update.append(p)
    if to_update:
        Product.objects.bulk_update(to_update, ["search_index"], batch_size=500)


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0003_trigram_search_indexes"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="search_index",
            field=models.CharField(
                blank=True, db_index=True, default="", max_length=400
            ),
        ),
        migrations.RunPython(backfill, migrations.RunPython.noop),
    ]
