# Generated by Django 5.1.15 on 2026-09-24 08:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0022_companysetting_trash_retention_days"),
        ("inventory", "0008_damagereport"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="StockCountSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "mode",
                    models.CharField(
                        choices=[
                            ("set", "Recuento total"),
                            ("add", "Sumar encontrado"),
                        ],
                        default="set",
                        max_length=10,
                    ),
                ),
                (
                    "reason",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="motivo"
                    ),
                ),
                ("products_count", models.PositiveIntegerField(default=0)),
                ("discrepancy_count", models.PositiveIntegerField(default=0)),
                (
                    "units_system",
                    models.DecimalField(decimal_places=2, default=0, max_digits=16),
                ),
                (
                    "units_final",
                    models.DecimalField(decimal_places=2, default=0, max_digits=16),
                ),
                (
                    "value_final",
                    models.DecimalField(decimal_places=2, default=0, max_digits=16),
                ),
                (
                    "value_diff",
                    models.DecimalField(decimal_places=2, default=0, max_digits=16),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "branch",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="stock_counts",
                        to="core.branch",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="stock_counts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "inventario (conteo)",
                "verbose_name_plural": "inventarios (conteos)",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="StockCountLine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sku", models.CharField(blank=True, max_length=64, null=True)),
                ("name", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "base_unit_label",
                    models.CharField(blank=True, max_length=40, null=True),
                ),
                (
                    "system_qty",
                    models.DecimalField(decimal_places=2, default=0, max_digits=16),
                ),
                (
                    "counted_qty",
                    models.DecimalField(decimal_places=2, default=0, max_digits=16),
                ),
                (
                    "final_qty",
                    models.DecimalField(decimal_places=2, default=0, max_digits=16),
                ),
                (
                    "difference",
                    models.DecimalField(decimal_places=2, default=0, max_digits=16),
                ),
                (
                    "unit_cost",
                    models.DecimalField(decimal_places=2, default=0, max_digits=14),
                ),
                (
                    "product",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="count_lines",
                        to="inventory.product",
                    ),
                ),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lines",
                        to="inventory.stockcountsession",
                    ),
                ),
            ],
            options={
                "verbose_name": "línea de inventario",
                "verbose_name_plural": "líneas de inventario",
                "ordering": ["id"],
            },
        ),
        migrations.AddIndex(
            model_name="stockcountsession",
            index=models.Index(
                fields=["branch", "created_at"], name="inventory_s_branch__92c1f8_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="stockcountline",
            index=models.Index(
                fields=["session"], name="inventory_s_session_99f6a7_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="stockcountline",
            index=models.Index(
                fields=["product"], name="inventory_s_product_6815b6_idx"
            ),
        ),
    ]
