# Generated by Django 5.1.15 on 2026-10-01 19:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0009_stockcountsession_stockcountline_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProductBarcode",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        db_index=True,
                        max_length=60,
                        unique=True,
                        verbose_name="código de barras",
                    ),
                ),
                (
                    "note",
                    models.CharField(
                        blank=True, max_length=120, null=True, verbose_name="nota"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="extra_barcodes",
                        to="inventory.product",
                    ),
                ),
            ],
            options={
                "verbose_name": "código de barras adicional",
                "verbose_name_plural": "códigos de barras adicionales",
                "ordering": ["id"],
            },
        ),
    ]
