# Generated by Django 5.1.15 on 2026-10-07 00:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0010_productbarcode"),
        ("partners", "0004_rebuild_search_index"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="supplier",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="products",
                to="partners.supplier",
                verbose_name="proveedor habitual",
            ),
        ),
    ]
