# Generated by Django 5.1.15 on 2026-10-07 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0011_product_supplier"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="pending_entry_qty",
            field=models.DecimalField(
                decimal_places=4,
                default=0,
                max_digits=14,
                verbose_name="pendiente de asignar a proveedor",
            ),
        ),
    ]
