# Generated by Django 5.1.15 on 2026-06-29 18:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0001_initial"),
        ("inventory", "0001_initial"),
        ("partners", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Purchase",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("folio", models.CharField(max_length=255, unique=True)),
                ("date", models.DateField(verbose_name="fecha")),
                (
                    "invoice_number",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="nº factura"
                    ),
                ),
                (
                    "subtotal",
                    models.DecimalField(decimal_places=2, default=0, max_digits=14),
                ),
                (
                    "tax",
                    models.DecimalField(
                        decimal_places=2, default=0, max_digits=14, verbose_name="IVA"
                    ),
                ),
                (
                    "total",
                    models.DecimalField(decimal_places=2, default=0, max_digits=14),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pendiente", "Pendiente"),
                            ("recibida", "Recibida"),
                            ("cancelada", "Cancelada"),
                        ],
                        default="pendiente",
                        max_length=20,
                    ),
                ),
                ("received_at", models.DateTimeField(blank=True, null=True)),
                (
                    "notes",
                    models.TextField(blank=True, null=True, verbose_name="notas"),
                ),
                (
                    "payment_status",
                    models.CharField(
                        choices=[
                            ("pagada", "Pagada"),
                            ("al_credito", "Al crédito"),
                            ("parcial", "Parcial"),
                        ],
                        default="pagada",
                        max_length=20,
                    ),
                ),
                (
                    "amount_paid",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=12,
                        verbose_name="monto pagado",
                    ),
                ),
                (
                    "due_date",
                    models.DateField(blank=True, null=True, verbose_name="vence"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "branch",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="purchases",
                        to="core.branch",
                    ),
                ),
                (
                    "supplier",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="purchases",
                        to="partners.supplier",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="purchases",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "compra",
                "verbose_name_plural": "compras",
                "ordering": ["-date", "-id"],
            },
        ),
        migrations.CreateModel(
            name="PurchaseItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "unit_cost",
                    models.DecimalField(
                        decimal_places=2, max_digits=12, verbose_name="costo unitario"
                    ),
                ),
                ("subtotal", models.DecimalField(decimal_places=2, max_digits=14)),
                ("tax_type", models.CharField(default="iva", max_length=20)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="purchase_items",
                        to="inventory.product",
                    ),
                ),
                (
                    "purchase",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="purchasing.purchase",
                    ),
                ),
            ],
            options={
                "verbose_name": "partida de compra",
                "verbose_name_plural": "partidas de compra",
            },
        ),
        migrations.CreateModel(
            name="PurchasePayment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(verbose_name="fecha")),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=12, verbose_name="monto"
                    ),
                ),
                (
                    "payment_method",
                    models.CharField(
                        default="efectivo", max_length=30, verbose_name="método"
                    ),
                ),
                (
                    "reference",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="referencia"
                    ),
                ),
                (
                    "notes",
                    models.TextField(blank=True, null=True, verbose_name="notas"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "purchase",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payments",
                        to="purchasing.purchase",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="purchase_payments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "pago de compra",
                "verbose_name_plural": "pagos de compra",
                "ordering": ["-date", "-id"],
            },
        ),
        migrations.AddIndex(
            model_name="purchase",
            index=models.Index(
                fields=["status", "date"], name="purchasing__status_8ee742_idx"
            ),
        ),
    ]
