# Generated by Django 5.1.15 on 2026-06-29 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CashMovement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("venta", "Venta"),
                            ("devolucion", "Devolución"),
                            ("ingreso", "Ingreso"),
                            ("egreso", "Egreso"),
                        ],
                        max_length=20,
                        verbose_name="tipo",
                    ),
                ),
                (
                    "payment_method",
                    models.CharField(
                        choices=[
                            ("efectivo", "Efectivo"),
                            ("tarjeta", "Tarjeta"),
                            ("transferencia", "Transferencia"),
                        ],
                        default="efectivo",
                        max_length=20,
                        verbose_name="método",
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=14, verbose_name="monto"
                    ),
                ),
                (
                    "description",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="descripción",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "movimiento de caja",
                "verbose_name_plural": "movimientos de caja",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="CashSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("opened_at", models.DateTimeField(verbose_name="abierta el")),
                (
                    "closed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="cerrada el"
                    ),
                ),
                (
                    "opening_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=14,
                        verbose_name="monto inicial",
                    ),
                ),
                (
                    "expected_cash",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=14,
                        verbose_name="efectivo esperado",
                    ),
                ),
                (
                    "counted_cash",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=14,
                        null=True,
                        verbose_name="efectivo contado",
                    ),
                ),
                (
                    "difference",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=14,
                        verbose_name="diferencia",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("abierta", "Abierta"), ("cerrada", "Cerrada")],
                        default="abierta",
                        max_length=20,
                    ),
                ),
                (
                    "opening_notes",
                    models.TextField(
                        blank=True, null=True, verbose_name="notas de apertura"
                    ),
                ),
                (
                    "closing_notes",
                    models.TextField(
                        blank=True, null=True, verbose_name="notas de cierre"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "sesión de caja",
                "verbose_name_plural": "sesiones de caja",
                "ordering": ["-opened_at"],
            },
        ),
    ]
