# Generated by Django 5.1.15 on 2026-06-29 18:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("cashbox", "0001_initial"),
        ("core", "0001_initial"),
        ("sales", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="cashmovement",
            name="sale",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="cash_movements",
                to="sales.sale",
            ),
        ),
        migrations.AddField(
            model_name="cashmovement",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="cash_movements",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="cashsession",
            name="branch",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="cash_sessions",
                to="core.branch",
            ),
        ),
        migrations.AddField(
            model_name="cashsession",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="cash_sessions",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="cashmovement",
            name="session",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="movements",
                to="cashbox.cashsession",
            ),
        ),
        migrations.AddIndex(
            model_name="cashsession",
            index=models.Index(
                fields=["user", "status"], name="cashbox_cas_user_id_4ac0ea_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="cashmovement",
            index=models.Index(
                fields=["session", "type"], name="cashbox_cas_session_41dfe4_idx"
            ),
        ),
    ]
