# Generated by Django 5.2.15 on 2026-07-01 07:31

from django.db import migrations, models

from partners.models import normalize_search


def backfill(apps, schema_editor):
    """Rellena search_index de los registros ya existentes."""
    Customer = apps.get_model("partners", "Customer")
    Supplier = apps.get_model("partners", "Supplier")
    for c in Customer.objects.all().iterator():
        c.search_index = normalize_search(c.name, c.tax_id, c.phone, c.email)
        c.save(update_fields=["search_index"])
    for s in Supplier.objects.all().iterator():
        s.search_index = normalize_search(s.name, s.tax_id, s.contact_name, s.phone, s.email)
        s.save(update_fields=["search_index"])


class Migration(migrations.Migration):

    dependencies = [
        ("partners", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="customer",
            name="search_index",
            field=models.CharField(
                blank=True, db_index=True, default="", max_length=600
            ),
        ),
        migrations.AddField(
            model_name="supplier",
            name="search_index",
            field=models.CharField(
                blank=True, db_index=True, default="", max_length=600
            ),
        ),
        migrations.RunPython(backfill, migrations.RunPython.noop),
    ]
