# Generated by Django 5.1.15 on 2026-06-29 21:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("sales", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ElectronicInvoice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "document_type",
                    models.CharField(
                        choices=[
                            ("FACT", "Factura"),
                            ("FCAM", "Factura cambiaria"),
                            ("NCRE", "Nota de crédito"),
                            ("NDEB", "Nota de débito"),
                            ("FPEQ", "Factura pequeño contribuyente"),
                        ],
                        default="FACT",
                        max_length=10,
                    ),
                ),
                (
                    "certificador",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("environment", models.CharField(default="PRUEBAS", max_length=20)),
                ("serie", models.CharField(blank=True, max_length=255, null=True)),
                ("numero", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "uuid",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        unique=True,
                        verbose_name="autorización SAT",
                    ),
                ),
                ("fecha_certificacion", models.DateTimeField(blank=True, null=True)),
                ("xml_generated", models.TextField(blank=True, null=True)),
                ("xml_signed", models.TextField(blank=True, null=True)),
                ("response_payload", models.JSONField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pendiente", "Pendiente"),
                            ("certificada", "Certificada"),
                            ("anulada", "Anulada"),
                            ("error", "Error"),
                        ],
                        default="pendiente",
                        max_length=20,
                    ),
                ),
                (
                    "error_message",
                    models.CharField(blank=True, max_length=500, null=True),
                ),
                ("anulada_at", models.DateTimeField(blank=True, null=True)),
                (
                    "anulacion_uuid",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "sale",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="electronic_invoice",
                        to="sales.sale",
                    ),
                ),
            ],
            options={
                "verbose_name": "factura electrónica",
                "verbose_name_plural": "facturas electrónicas",
                "ordering": ["-id"],
                "indexes": [
                    models.Index(
                        fields=["status"], name="billing_ele_status_65c269_idx"
                    )
                ],
            },
        ),
    ]
