# Generated by Django 5.2.15 on 2026-07-02 07:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("billing", "0001_initial"),
        ("salereturns", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="CreditNote",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("document_type", models.CharField(default="NCRE", max_length=10)),
                (
                    "certificador",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("environment", models.CharField(default="PRUEBAS", max_length=20)),
                ("serie", models.CharField(blank=True, max_length=255, null=True)),
                ("numero", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "uuid",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        unique=True,
                        verbose_name="autorización SAT",
                    ),
                ),
                ("fecha_certificacion", models.DateTimeField(blank=True, null=True)),
                ("motivo", models.CharField(blank=True, max_length=255, null=True)),
                ("xml_generated", models.TextField(blank=True, null=True)),
                ("xml_signed", models.TextField(blank=True, null=True)),
                ("response_payload", models.JSONField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pendiente", "Pendiente"),
                            ("certificada", "Certificada"),
                            ("anulada", "Anulada"),
                            ("error", "Error"),
                        ],
                        default="pendiente",
                        max_length=20,
                    ),
                ),
                (
                    "error_message",
                    models.CharField(blank=True, max_length=500, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "invoice",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="credit_notes",
                        to="billing.electronicinvoice",
                    ),
                ),
                (
                    "sale_return",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="credit_note",
                        to="salereturns.salereturn",
                    ),
                ),
            ],
            options={
                "verbose_name": "nota de crédito electrónica",
                "verbose_name_plural": "notas de crédito electrónicas",
                "ordering": ["-id"],
            },
        ),
    ]
