# Generated by Django 5.2.15 on 2026-07-04 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("billing", "0002_creditnote"),
    ]

    operations = [
        migrations.AlterField(
            model_name="electronicinvoice",
            name="document_type",
            field=models.CharField(
                choices=[
                    ("FACT", "Factura"),
                    ("FCAM", "Factura cambiaria"),
                    ("NCRE", "Nota de crédito"),
                    ("NDEB", "Nota de débito"),
                    ("FPEQ", "Factura pequeño contribuyente"),
                    ("FCAP", "Factura cambiaria pequeño contribuyente"),
                ],
                default="FACT",
                max_length=10,
            ),
        ),
    ]
