# Generated by Django 5.2.15 on 2026-07-23 23:45

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("audit", "0001_initial"),
        ("core", "0007_user_is_device"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="auditlog",
            index=models.Index(
                fields=["auditable_type", "auditable_id"],
                name="audit_audit_auditab_6328fd_idx",
            ),
        ),
    ]
